packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/*'
  - 'tools/*'
allowBuilds:
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
patchedDependencies:
  '@pipeit/core@0.2.7': patches/@pipeit__core@0.2.7.patch
peerDependencyRules:
  allowedVersions:
    '@solana-program/compute-budget': 0.15.0
    '@solana/sysvars': 6.9.0
    eslint: 10.4.0
    typescript: 6.0.3
    utf-8-validate: 6.0.6
